name: Deploying project on GH Pages

on:
  push:
     branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Running ls
        run: ls -al
